### ISSUE TITLE
Dashboard Keep Loading

### ISSUE THREAD

**Issue by moicw** [FressicMY/fressic-public-issues#1]
**Describe the bug**
Dashboard Keep Loading

**To Reproduce**
1. Click Home Page

**Expected behavior**
Display banner or song/artist/album list

**Screenshots**
![image](https://user-images.githubusercontent.com/35769244/132362546-f08f2448-d72d-4adf-8539-a529170112f5.png)

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 9
 - OS: Android 
 - Version: 28
 - App Version: 0.5.2

**Additional context**

**Comment by Mayb3Nots** [comment]
fixed via e96f27a91f1fa2d083d6932e59aa7a1a43669ed0
