### ISSUE TITLE
Playlist quantity does not match

### ISSUE THREAD

**Issue by moicw** [FressicMY/fressic-public-issues#5]
**Describe the bug**
Playlist quantity on profile page does not match with the playlist. It will only updated after restart the app

**To Reproduce**
1. Go to Profile Page, 
2. Click on New Playlist
3. Create New playlist 1
4. Click on New Playlist
5. Create New playlist 2
6. Playlist quantity on top does not change

**Expected behavior**
Playlist quantity shall update accordingly. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35769244/132371808-5309a592-934d-4230-823b-3813fad942f1.png)

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 9
 - OS: Android
 - Version: 28
 - App Version: 0.5.2

**Additional context**

**Comment by Mayb3Nots** [comment]
fixed via 527d1e28c21ddda41995cc49c698366d996bf0a8
