### ISSUE TITLE
Forget Password Keep Loading

### ISSUE THREAD

**Issue by moicw** [FressicMY/fressic-public-issues#6]
**Describe the bug**
Keep loading after click send reset link, but have received email to reset password

**To Reproduce**
1. Go to Forgot Password and fill in email address
2. Click on send reset link
3. Keep Loading

**Expected behavior**
Should show reset link have been send to email

**Screenshots**
![image](https://user-images.githubusercontent.com/35769244/132375778-b08646a2-1de2-4bc2-9d9e-a6d90afb84a0.png)

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 9
 - OS: Android
 - Version: 28
 - App Version 0.5.2

**Additional context**

**Comment by Mayb3Nots** [comment]
fixed via 45877678e3e73af094963e1cd75fa0400841c511
